INSERT INTO permissions (name, value) VALUES
    ('CREATE_TICKET', true),
    ('READ_TICKET', true),
    ('DELETE_TICKET', true),
    ('CREATE_AWB', true),
    ('READ_AWB', true),
    ('DELETE_AWB', true),
    ('CREATE_ACCOUNT', true),
    ('READ_ACCOUNT', true),
    ('DELETE_ACCOUNT', true),
    ('CREATE_CITY', true),
    ('READ_CITY', true),
    ('DELETE_CITY', true),
    ('CREATE_COUNTRY', true),
    ('READ_COUNTRY', true),
    ('DELETE_COUNTRY', true),
    ('CREATE_DEPARTMENT', true),
    ('READ_DEPARTMENT', true),
    ('DELETE_DEPARTMENT', true),
    ('CREATE_DEPARTMENT_CATEGORY', true),
    ('READ_DEPARTMENT_CATEGORY', true),
    ('DELETE_DEPARTMENT_CATEGORY', true),
    ('CREATE_PRODUCT_TYPE', true),
    ('READ_PRODUCT_TYPE', true),
    ('DELETE_PRODUCT_TYPE', true),
    ('CREATE_SERVICE_TYPE', true),
    ('READ_SERVICE_TYPE', true),
    ('DELETE_SERVICE_TYPE', true),
    ('DASHBOARD', true),
    ('PERMISSION', true),
    ('CREATE_USER', true),
    ('READ_USER', true),
    ('DELETE_USER', true);

    INSERT INTO roles
    VALUES
        (1,'ROLE_ADMIN'),
        (2,'ROLE_OPERATION_AGENT'),
        (3,'ROLE_CUSTOMER_SERVICE_AGENT'),
        (4,'ROLE_CUSTOMER_CARE_AGENT'),
        (5,'ROLE_MANAGEMENT_USER'),
        (6,'ROLE_OPERATION_USER'),
        (7,'ROLE_CUSTOMER_USER'),
        (8,'ROLE_SALES_AGENT');


INSERT INTO `role_permissions` VALUES
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_TICKET')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_TICKET')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_TICKET')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_AWB')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_AWB')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_AWB')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_ACCOUNT')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_ACCOUNT')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_ACCOUNT')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_CITY')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_CITY')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_CITY')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_COUNTRY')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_COUNTRY')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_COUNTRY')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_DEPARTMENT')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_DEPARTMENT')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_DEPARTMENT')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_DEPARTMENT_CATEGORY')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_DEPARTMENT_CATEGORY')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_DEPARTMENT_CATEGORY')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_PRODUCT_TYPE')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_PRODUCT_TYPE')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_PRODUCT_TYPE')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_SERVICE_TYPE')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_SERVICE_TYPE')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_SERVICE_TYPE')),
    (1, (SELECT id FROM permissions WHERE name = 'DASHBOARD')),
    (1, (SELECT id FROM permissions WHERE name = 'PERMISSION')),
    (1, (SELECT id FROM permissions WHERE name = 'CREATE_USER')),
    (1, (SELECT id FROM permissions WHERE name = 'READ_USER')),
    (1, (SELECT id FROM permissions WHERE name = 'DELETE_USER'));

--INSERT INTO country (name, status)
--VALUES
--  ('Pakistan', true),
--  ('India', true),
--  ('Saudi Arabia', true),
--  ('United States', true),
--  ('United Kingdom', true),
--  ('Canada', true),
--  ('Australia', true),
--  ('Germany', true),
--  ('France', true),
--  ('Japan', true);


INSERT INTO country (id, name, status, alpha_code, code)
VALUES
(1, 'Afghanistan', true, 'AFG', 004),
(2, 'Åland Islands', true, 'ALA', 248),
(3, 'Albania', true, 'ALB', 008),
(4, 'Algeria', true, 'DZA', 012),
(5, 'American Samoa', true, 'ASM', 016),
(6, 'Andorra', true, 'AND', 020),
(7, 'Angola', true, 'AGO', 024),
(8, 'Anguilla', true, 'AIA', 660),
(9, 'Antarctica', true, 'ATA', 010),
(10, 'Antigua and Barbuda', true, 'ATG', 028),
(11, 'Argentina', true, 'ARG', 032),
(12, 'Armenia', true, 'ARM', 051),
(13, 'Aruba', true, 'ABW', 533),
(14, 'Australia', true, 'AUS', 036),
(15, 'Austria', true, 'AUT', 040),
(16, 'Azerbaijan', true, 'AZE', 031),
(17, 'Bahamas', true, 'BHS', 044),
(18, 'Bahrain', true, 'BHR', 048),
(19, 'Bangladesh', true, 'BGD', 050),
(20, 'Barbados', true, 'BRB', 052),
(21, 'Belarus', true, 'BLR', 112),
(22, 'Belgium', true, 'BEL', 056),
(23, 'Belize', true, 'BLZ', 084),
(24, 'Benin', true, 'BEN', 204),
(25, 'Bermuda', true, 'BMU', 060),
(26, 'Bhutan', true, 'BTN', 064),
(27, 'Bolivia (Plurinational State of)', true, 'BOL', 068),
(28, 'Bonaire, Sint Eustatius and Saba', true, 'BES', 535),
(29, 'Bosnia and Herzegovina', true, 'BIH', 070),
(30, 'Botswana', true, 'BWA', 072),
(31, 'Bouvet Island', true, 'BVT', 074),
(32, 'Brazil', true, 'BRA', 076),
(33, 'British Indian Ocean Territory', true, 'IOT', 086),
(34, 'British Virgin Islands', true, 'VGB', 092),
(35, 'Brunei Darussalam', true, 'BRN', 096),
(36, 'Bulgaria', true, 'BGR', 100),
(37, 'Burkina Faso', true, 'BFA', 854),
(38, 'Burundi', true, 'BDI', 108),
(39, 'Cabo Verde', true, 'CPV', 132),
(40, 'Cambodia', true, 'KHM', 116),
(41, 'Cameroon', true, 'CMR', 120),
(42, 'Canada', true, 'CAN', 124),
(43, 'Cayman Islands', true, 'CYM', 136),
(44, 'Central African Republic', true, 'CAF', 140),
(45, 'Chad', true, 'TCD', 148),
(46, 'Chile', true, 'CHL', 152),
(47, 'China', true, 'CHN', 156),
(48, 'China, Hong Kong Special Administrative Region', true, 'HKG', 344),
(49, 'China, Macao Special Administrative Region', true, 'MAC', 446),
(50, 'Christmas Island', true, 'CXR', 162),
(51, 'Cocos (Keeling) Islands', true, 'CCK', 166),
(52, 'Colombia', true, 'COL', 170),
(53, 'Comoros', true, 'COM', 174),
(54, 'Congo', true, 'COG', 178),
(55, 'Cook Islands', true, 'COK', 184),
(56, 'Costa Rica', true, 'CRI', 188),
(57, 'Côte d’Ivoire', true, 'CIV', 384),
(58, 'Croatia', true, 'HRV', 191),
(59, 'Cuba', true, 'CUB', 192),
(60, 'Curaçao', true, 'CUW', 531),
(61, 'Cyprus', true, 'CYP', 196),
(62, 'Czechia', true, 'CZE', 203),
(63, 'Democratic People''s Republic of Korea', true, 'PRK', 408),
(64, 'Democratic Republic of the Congo', true, 'COD', 180),
(65, 'Denmark', true, 'DNK', 208),
(66, 'Djibouti', true, 'DJI', 262),
(67, 'Dominica', true, 'DMA', 212),
(68, 'Dominican Republic', true, 'DOM', 214),
(69, 'Ecuador', true, 'ECU', 218),
(70, 'Egypt', true, 'EGY', 818),
(71, 'El Salvador', true, 'SLV', 222),
(72, 'Equatorial Guinea', true, 'GNQ', 226),
(73, 'Eritrea', true, 'ERI', 232),
(74, 'Estonia', true, 'EST', 233),
(75, 'Eswatini', true, 'SWZ', 748),
(76, 'Ethiopia', true, 'ETH', 231),
(77, 'Falkland Islands (Malvinas)', true, 'FLK', 238),
(78, 'Faroe Islands', true, 'FRO', 234),
(79, 'Fiji', true, 'FJI', 242),
(80, 'Finland', true, 'FIN', 246),
(81, 'France', true, 'FRA', 250),
(82, 'French Guiana', true, 'GUF', 254),
(83, 'French Polynesia', true, 'PYF', 258),
(84, 'French Southern Territories', true, 'ATF', 260),
(85, 'Gabon', true, 'GAB', 266),
(86, 'Gambia', true, 'GMB', 270),
(87, 'Georgia', true, 'GEO', 268),
(88, 'Germany', true, 'DEU', 276),
(89, 'Ghana', true, 'GHA', 288),
(90, 'Gibraltar', true, 'GIB', 292),
(91, 'Greece', true, 'GRC', 300),
(92, 'Greenland', true, 'GRL', 304),
(93, 'Grenada', true, 'GRD', 308),
(94, 'Guadeloupe', true, 'GLP', 312),
(95, 'Guam', true, 'GUM', 316),
(96, 'Guatemala', true, 'GTM', 320),
(97, 'Guernsey', true, 'GGY', 831),
(98, 'Guinea', true, 'GIN', 324),
(99, 'Guinea-Bissau', true, 'GNB', 624),
(100, 'Guyana', true, 'GUY', 328),
(101, 'Haiti', true, 'HTI', 332),
(102, 'Heard Island and McDonald Islands', true, 'HMD', 334),
(103, 'Holy See', true, 'VAT', 336),
(104, 'Honduras', true, 'HND', 340),
(105, 'Hungary', true, 'HUN', 348),
(106, 'Iceland', true, 'ISL', 352),
(107, 'India', true, 'IND', 356),
(108, 'Indonesia', true, 'IDN', 360),
(109, 'Iran (Islamic Republic of)', true, 'IRN', 364),
(110, 'Iraq', true, 'IRQ', 368),
(111, 'Ireland', true, 'IRL', 372),
(112, 'Isle of Man', true, 'IMN', 833),
(113, 'Israel', true, 'ISR', 376),
(114, 'Italy', true, 'ITA', 380),
(115, 'Jamaica', true, 'JAM', 388),
(116, 'Japan', true, 'JPN', 392),
(117, 'Jersey', true, 'JEY', 832),
(118, 'Jordan', true, 'JOR', 400),
(119, 'Kazakhstan', true, 'KAZ', 398),
(120, 'Kenya', true, 'KEN', 404),
(121, 'Kiribati', true, 'KIR', 296),
(122, 'Kuwait', true, 'KWT', 414),
(123, 'Kyrgyzstan', true, 'KGZ', 417),
(124, 'Lao People''s Democratic Republic', true, 'LAO', 418),
(125, 'Latvia', true, 'LVA', 428),
(126, 'Lebanon', true, 'LBN', 422),
(127, 'Lesotho', true, 'LSO', 426),
(128, 'Liberia', true, 'LBR', 430),
(129, 'Libya', true, 'LBY', 434),
(130, 'Liechtenstein', true, 'LIE', 438),
(131, 'Lithuania', true, 'LTU', 440),
(132, 'Luxembourg', true, 'LUX', 442),
(133, 'Madagascar', true, 'MDG', 450),
(134, 'Malawi', true, 'MWI', 454),
(135, 'Malaysia', true, 'MYS', 458),
(136, 'Maldives', true, 'MDV', 462),
(137, 'Mali', true, 'MLI', 466),
(138, 'Malta', true, 'MLT', 470),
(139, 'Marshall Islands', true, 'MHL', 584),
(140, 'Martinique', true, 'MTQ', 474),
(141, 'Mauritania', true, 'MRT', 478),
(142, 'Mauritius', true, 'MUS', 480),
(143, 'Mayotte', true, 'MYT', 175),
(144, 'Mexico', true, 'MEX', 484),
(145, 'Micronesia (Federated States of)', true, 'FSM', 583),
(146, 'Monaco', true, 'MCO', 492),
(147, 'Mongolia', true, 'MNG', 496),
(148, 'Montenegro', true, 'MNE', 499),
(149, 'Montserrat', true, 'MSR', 500),
(150, 'Morocco', true, 'MAR', 504),
(151, 'Mozambique', true, 'MOZ', 508),
(152, 'Myanmar', true, 'MMR', 104),
(153, 'Namibia', true, 'NAM', 516),
(154, 'Nauru', true, 'NRU', 520),
(155, 'Nepal', true, 'NPL', 524),
(156, 'Netherlands (Kingdom of the)', true, 'NLD', 528),
(157, 'New Caledonia', true, 'NCL', 540),
(158, 'New Zealand', true, 'NZL', 554),
(159, 'Nicaragua', true, 'NIC', 558),
(160, 'Niger', true, 'NER', 562),
(161, 'Nigeria', true, 'NGA', 566),
(162, 'Niue', true, 'NIU', 570),
(163, 'Norfolk Island', true, 'NFK', 574),
(164, 'North Macedonia', true, 'MKD', 807),
(165, 'Northern Mariana Islands', true, 'MNP', 580),
(166, 'Norway', true, 'NOR', 578),
(167, 'Oman', true, 'OMN', 512),
(168, 'Pakistan', true, 'PAK', 586),
(169, 'Palau', true, 'PLW', 585),
(170, 'Panama', true, 'PAN', 591),
(171, 'Papua New Guinea', true, 'PNG', 598),
(172, 'Paraguay', true, 'PRY', 600),
(173, 'Peru', true, 'PER', 604),
(174, 'Philippines', true, 'PHL', 608),
(175, 'Pitcairn', true, 'PCN', 612),
(176, 'Poland', true, 'POL', 616),
(177, 'Portugal', true, 'PRT', 620),
(178, 'Puerto Rico', true, 'PRI', 630),
(179, 'Qatar', true, 'QAT', 634),
(180, 'Republic of Korea', true, 'KOR', 410),
(181, 'Republic of Moldova', true, 'MDA', 498),
(182, 'Réunion', true, 'REU', 638),
(183, 'Romania', true, 'ROU', 642),
(184, 'Russian Federation', true, 'RUS', 643),
(185, 'Rwanda', true, 'RWA', 646),
(186, 'Saint Barthélemy', true, 'BLM', 652),
(187, 'Saint Helena', true, 'SHN', 654),
(188, 'Saint Kitts and Nevis', true, 'KNA', 659),
(189, 'Saint Lucia', true, 'LCA', 662),
(190, 'Saint Martin (French Part)', true, 'MAF', 663),
(191, 'Saint Pierre and Miquelon', true, 'SPM', 666),
(192, 'Saint Vincent and the Grenadines', true, 'VCT', 670),
(193, 'Samoa', true, 'WSM', 882),
(194, 'San Marino', true, 'SMR', 674),
(195, 'Sao Tome and Principe', true, 'STP', 678),
(196, 'Saudi Arabia', true, 'SAU', 682),
(197, 'Senegal', true, 'SEN', 686),
(198, 'Serbia', true, 'SRB', 688),
(199, 'Seychelles', true, 'SYC', 690),
(200, 'Sierra Leone', true, 'SLE', 694),
(201, 'Singapore', true, 'SGP', 702),
(202, 'Sint Maarten (Dutch part)', true, 'SXM', 534),
(203, 'Slovakia', true, 'SVK', 703),
(204, 'Slovenia', true, 'SVN', 705),
(205, 'Solomon Islands', true, 'SLB', 90),
(206, 'Somalia', true, 'SOM', 706),
(207, 'South Africa', true, 'ZAF', 710),
(208, 'South Georgia and the South Sandwich Islands', true, 'SGS', 239),
(209, 'South Sudan', true, 'SSD', 728),
(210, 'Spain', true, 'ESP', 724),
(211, 'Sri Lanka', true, 'LKA', 144),
(212, 'State of Palestine', true, 'PSE', 275),
(213, 'Sudan', true, 'SDN', 729),
(214, 'Suriname', true, 'SUR', 740),
(215, 'Svalbard and Jan Mayen Islands', true, 'SJM', 744),
(216, 'Sweden', true, 'SWE', 752),
(217, 'Switzerland', true, 'CHE', 756),
(218, 'Syrian Arab Republic', true, 'SYR', 760),
(219, 'Tajikistan', true, 'TJK', 762),
(220, 'Thailand', true, 'THA', 764),
(221, 'Timor-Leste', true, 'TLS', 626),
(222, 'Togo', true, 'TGO', 768),
(223, 'Tokelau', true, 'TKL', 772),
(224, 'Tonga', true, 'TON', 776),
(225, 'Trinidad and Tobago', true, 'TTO', 780),
(226, 'Tunisia', true, 'TUN', 788),
(227, 'Türkiye', true, 'TUR', 792),
(228, 'Turkmenistan', true, 'TKM', 795),
(229, 'Turks and Caicos Islands', true, 'TCA', 796),
(230, 'Tuvalu', true, 'TUV', 798),
(231, 'Uganda', true, 'UGA', 800),
(232, 'Ukraine', true, 'UKR', 804),
(233, 'United Arab Emirates', true, 'ARE', 784),
(234, 'United Kingdom of Great Britain and Northern Ireland', true, 'GBR', 826),
(235, 'United Republic of Tanzania', true, 'TZA', 834),
(236, 'United States Minor Outlying Islands', true, 'UMI', 581),
(237, 'United States of America', true, 'USA', 840),
(238, 'United States Virgin Islands', true, 'VIR', 850),
(239, 'Uruguay', true, 'URY', 858),
(240, 'Uzbekistan', true, 'UZB', 860),
(241, 'Vanuatu', true, 'VUT', 548),
(242, 'Venezuela (Bolivarian Republic of)', true, 'VEN', 862),
(243, 'Viet Nam', true, 'VNM', 704),
(244, 'Wallis and Futuna Islands', true, 'WLF', 876),
(245, 'Western Sahara', true, 'ESH', 732),
(246, 'Yemen', true, 'YEM', 887),
(247, 'Zambia', true, 'ZMB', 894),
(248, 'Zimbabwe', true, 'ZWE', 716);



--INSERT INTO city (name, status, country_id)
--VALUES
--  ('Islamabad', true, (SELECT id FROM country WHERE name = 'Pakistan')),
--  ('Karachi', true, (SELECT id FROM country WHERE name = 'Pakistan')),
--  ('Lahore', true, (SELECT id FROM country WHERE name = 'Pakistan')),
--
--  ('New Delhi', true, (SELECT id FROM country WHERE name = 'India')),
--  ('Mumbai', true, (SELECT id FROM country WHERE name = 'India')),
--  ('Bangalore', true, (SELECT id FROM country WHERE name = 'India')),
--
--  ('Riyadh', true, (SELECT id FROM country WHERE name = 'Saudi Arabia')),
--  ('Jeddah', true, (SELECT id FROM country WHERE name = 'Saudi Arabia')),
--  ('Dammam', true, (SELECT id FROM country WHERE name = 'Saudi Arabia')),
--
--  ('New York', true, (SELECT id FROM country WHERE name = 'United States')),
--  ('Los Angeles', true, (SELECT id FROM country WHERE name = 'United States')),
--  ('Chicago', true, (SELECT id FROM country WHERE name = 'United States')),
--
--  ('London', true, (SELECT id FROM country WHERE name = 'United Kingdom')),
--  ('Manchester', true, (SELECT id FROM country WHERE name = 'United Kingdom')),
--  ('Birmingham', true, (SELECT id FROM country WHERE name = 'United Kingdom')),
--
--  ('Toronto', true, (SELECT id FROM country WHERE name = 'Canada')),
--  ('Vancouver', true, (SELECT id FROM country WHERE name = 'Canada')),
--  ('Montreal', true, (SELECT id FROM country WHERE name = 'Canada')),
--
--  ('Sydney', true, (SELECT id FROM country WHERE name = 'Australia')),
--  ('Melbourne', true, (SELECT id FROM country WHERE name = 'Australia')),
--  ('Brisbane', true, (SELECT id FROM country WHERE name = 'Australia')),
--
--  ('Berlin', true, (SELECT id FROM country WHERE name = 'Germany')),
--  ('Munich', true, (SELECT id FROM country WHERE name = 'Germany')),
--  ('Hamburg', true, (SELECT id FROM country WHERE name = 'Germany')),
--
--  ('Paris', true, (SELECT id FROM country WHERE name = 'France')),
--  ('Marseille', true, (SELECT id FROM country WHERE name = 'France')),
--  ('Lyon', true, (SELECT id FROM country WHERE name = 'France')),
--
--  ('Tokyo', true, (SELECT id FROM country WHERE name = 'Japan')),
--  ('Osaka', true, (SELECT id FROM country WHERE name = 'Japan')),
--  ('Kyoto', true, (SELECT id FROM country WHERE name = 'Japan'));


INSERT INTO city (id, name, status, country_id)
VALUES


INSERT INTO department (name, status)
VALUES
  ('Customer Service', true),
  ('Customer Care', true),
  ('Finance', true),
  ('Operation', true),
  ('IT', true),
  ('Admin', true),
  ('HR and Legal', true),
  ('Quality and Security', true);


INSERT INTO department_category (name, status, department_id)
VALUES
  -- Customer Care
  ('Call Back', true, (SELECT id FROM department WHERE name = 'Customer Care')),
  ('Customer Care Case', true, (SELECT id FROM department WHERE name = 'Customer Care')),

  -- Finance
  ('Billing', true, (SELECT id FROM department WHERE name = 'Finance')),
  ('Refund', true, (SELECT id FROM department WHERE name = 'Finance')),
  ('Collection', true, (SELECT id FROM department WHERE name = 'Finance')),

  -- Operation
  ('Urgent Delivery', true, (SELECT id FROM department WHERE name = 'Operation')),
  ('Delivery Complaint', true, (SELECT id FROM department WHERE name = 'Operation')),
  ('Pickup Request', true, (SELECT id FROM department WHERE name = 'Operation')),
  ('Address Update', true, (SELECT id FROM department WHERE name = 'Operation')),
  ('Schedule Delivery', true, (SELECT id FROM department WHERE name = 'Operation')),
  ('Services Request', true, (SELECT id FROM department WHERE name = 'Operation')),

  -- IT
  ('Technical Issue', true, (SELECT id FROM department WHERE name = 'IT')),
  ('Contact Customer', true, (SELECT id FROM department WHERE name = 'IT')),

  -- Admin
  ('Call Back', true, (SELECT id FROM department WHERE name = 'Admin')),

  -- HR & Legal
  ('Call Back', true, (SELECT id FROM department WHERE name = 'HR and Legal')),

  -- Quality & Security
  ('Call Back', true, (SELECT id FROM department WHERE name = 'Quality and Security'));


INSERT INTO product_type (code, name, status)
VALUES
  ('DS', 'Domestic Shipping', true),
  ('IS', 'International Shipping', true),
  ('CDC', 'Customized Delivery Channel', true),
  ('SC', 'Sea Cargo', true);


INSERT INTO service_type (code, name, status, product_type_id)
VALUES
  -- Domestic Shipping
  ('SDPR', 'SALSEL Domestic Priority', true, (SELECT id FROM product_type WHERE code = 'DS')),
  ('SDEX', 'SALSEL Domestic Express', true, (SELECT id FROM product_type WHERE code = 'DS')),
  ('SDLF', 'SALSEL Domestic Loose Freight', true, (SELECT id FROM product_type WHERE code = 'DS')),
  ('SDPF', 'SALSEL Domestic Pallet Freight', true, (SELECT id FROM product_type WHERE code = 'DS')),
  ('SDCS', 'SALSEL Domestic Cargo Shipping', true, (SELECT id FROM product_type WHERE code = 'DS')),

  -- International Shipping
  ('SIPR', 'SALSEL International Priority', true, (SELECT id FROM product_type WHERE code = 'IS')),
  ('SIEX', 'SALSEL International Express', true, (SELECT id FROM product_type WHERE code = 'IS')),
  ('SIPS', 'SALSEL International Promo Service', true, (SELECT id FROM product_type WHERE code = 'IS')),
  ('SIGS', 'SALSEL International Ground Shipping', true, (SELECT id FROM product_type WHERE code = 'IS')),

  -- Customized Delivery Channel
  ('SBDS', 'SALSEL Bullet Delivery Service', true, (SELECT id FROM product_type WHERE code = 'CDC')),
  ('SSDS', 'SALSEL Same Day Service', true, (SELECT id FROM product_type WHERE code = 'CDC')),
  ('SSDE', 'SALSEL Special Delivery Express', true, (SELECT id FROM product_type WHERE code = 'CDC')),

  -- Sea Cargo
  ('SSCD', 'SALSEL Sea Cargo Freight Clearance & Delivery', true, (SELECT id FROM product_type WHERE code = 'SC')),
  ('SSFT', 'SALSEL Sea Cargo Freight Transport', true, (SELECT id FROM product_type WHERE code = 'SC')),
  ('SSFC', 'SALSEL Sea Cargo Freight Clearance', true, (SELECT id FROM product_type WHERE code = 'SC'));


INSERT INTO product_field (name, sequence, status, created_at, type)
VALUES
  ('Category', 1, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Ticket Flag', 2, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Ticket Status', 3, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Currency', 4, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Duty And Tax Billing', 5, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Ticket Type', 6, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Status', 7, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Request Type', 8, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Account Types', 9, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Sales Region', 10, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Sales Agent', 11, 'Active', CURRENT_DATE, 'MULTIDROPDOWN'),
  ('Awb Status', 12, 'Active', CURRENT_DATE, 'MULTIDROPDOWN');


INSERT INTO product_field_values (name, status, product_field_id)
VALUES
    ('Complaint', 'Active', 1),
    ('Suggestion', 'Active', 1),
    ('General Inquiry', 'Active', 1),
    ('Service Request', 'Active', 1),

    ('Normal', 'Active', 2),
    ('Priority', 'Active', 2),
    ('Urgent', 'Active',2),
    ('Extreme Urgent', 'Active',2),

    ('Open', 'Active', 3),
    ('Closed', 'Active', 3),
    ('On-Hold', 'Active', 3),
    ('Under Process', 'Active', 3),
    ('Overdue Escalation', 'Active', 3),
    ('Held-FI', 'Active', 3),

    ('SAR', 'Active', 4),
    ('AED', 'Active', 4),
    ('BHD', 'Active', 4),
    ('KWD', 'Active', 4),
    ('OMR', 'Active', 4),
    ('SDG', 'Active', 4),
    ('CNY', 'Active', 4),
    ('USD', 'Active', 4),

    ('Bill Shipper', 'Active', 5),
    ('Bill Consignee', 'Active', 5),

    ('Shipment Inquiry', 'Active', 6),
    ('Pickup Request', 'Active', 6),
    ('Rate Inquiry', 'Active', 6),
    ('Pre Sales Request', 'Active', 6),
    ('Account Opening Request', 'Active', 6),
    ('Exclusive Partnership Program', 'Active', 6),

    ('Active', 'Active', 7),
    ('In Active', 'Active', 7),

    ('Pick-up', 'Active', 8),
    ('Drop-off', 'Active', 8),

    ('Cash', 'Active', 9),
    ('Corporate', 'Active', 9),
    ('ECOM', 'Active', 9),
    ('Freight', 'Active', 9),
    ('Cash Retail', 'Active', 9),
    ('Freight B2B', 'Active', 9),
    ('Freight BCB', 'Active', 9),

    ('Saudi Arabia', 'Active', 10),
    ('United Arab Emirates', 'Active', 10),
    ('GCC Other', 'Active', 10),
    ('Sudan', 'Active', 10),
    ('Africa', 'Active', 10),
    ('Turkey', 'Active', 10),
    ('Middle East', 'Active', 10),
    ('United States of America', 'Active', 10),
    ('UK & Europe', 'Active', 10),
    ('China', 'Active', 10),

    ('Mohammad Sameer', 'Active', 11),

    ('AWB Created', 'Active', 12),
    ('Picked Up', 'Active', 12),
    ('Arrived in Station', 'Active', 12),
    ('Held in Station', 'Active', 12),
    ('Depart from Station', 'Active', 12),
    ('Arrived in Hub', 'Active', 12),
    ('Depart from Hub', 'Active', 12),
    ('Out for Delivery', 'Active', 12),
    ('Delivered', 'Active', 12);


INSERT INTO users VALUES (1,'Salsel@maildrop.cc','001',"new","Person","admin","$2a$12$mHLYj8pQvDPZq1J2hcevUuNYnJT.tzdlZbzokF1n4LBFwpPIxLSoC","03353183327", true);

INSERT INTO user_roles VALUES (1,1);
